# Generated by Django 5.2.14 on 2026-05-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_userprofile_is_admin_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrecord',
            name='order_status',
            field=models.CharField(choices=[('Queued', 'Queued'), ('Preparing', 'Preparing'), ('Ready for pickup', 'Ready for pickup'), ('Picked up', 'Picked up'), ('Cancelled', 'Cancelled')], default='Queued', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderrecord',
            name='payment_status',
            field=models.CharField(choices=[('Pending payment', 'Pending payment'), ('Payment received', 'Payment received'), ('Refunded', 'Refunded')], default='Pending payment', max_length=30),
        ),
    ]
