# Generated by Django 5.2.14 on 2026-05-31 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_menuitem_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
